version: "3.9"
services:
  api:
    build: ./packages/api
    ports:
      - "5000:5000"
    links:
      - redis
  frontend:
    build: ./packages/client
    ports:
      - "5001:5001"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
